name: Docker Image CI

on: push

jobs:
  docker-image:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      name: checkout code
    - uses: actions/checkout@v2
    
    - name: Run docker-image
      uses: github/super-linter@v3
      env:
      DEFAULT _BRANCH:main
      GITHUB _TOKEN: ${{ secret.GITHUB_TOKEN}}
